trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: ArtifactsSecrets

steps:

# Install Azure CLI
- script: |
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  displayName: Install Azure CLI

# Install Azure DevOps Extension
- script: |
    az extension add --name azure-devops --yes || true
    az extension update --name azure-devops
  displayName: Install Azure DevOps Extension

# Download Universal Package
- script: |

    echo "Logging into Azure DevOps..."

    echo "$(AZURE_DEVOPS_EXT_PAT)" | az devops login

    echo "Configuring defaults..."

    az devops configure --defaults \
      organization=https://dev.azure.com/akparashar9597 \
      project=Artifacts-Demo1

    echo "Downloading package..."

    az artifacts universal download \
      --organization https://dev.azure.com/akparashar9597 \
      --scope project \
      --project Artifacts-Demo1 \
      --feed PythonFeed \
      --name pythonapp \
      --version "*" \
      --path download

  env:
    AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)

  displayName: Download Universal Package

# Verify Download
- script: |
    echo "Downloaded Files:"
    ls -R download
  displayName: Verify Download
